ccflags-y += -I$(src)/support_ic

ccflags-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83112F) += -D__HIMAX_HX83112_MOD__ -DHX_FIX_TOUCH_INFO -DHX_112F_SET -DFIX_WVLA -I$(src)/support_ic/himax_0flash_mmi_hx83112f
ccflags-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83112) += -D__HIMAX_HX83112_MOD__ -I$(src)/support_ic/himax_0flash_mmi_hx83112
ccflags-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83102) += -D__HIMAX_HX83102_MOD__ -I$(src)/support_ic/himax_0flash_mmi_hx83102
ccflags-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83102D) += -D__HIMAX_HX83102D_MOD__ -DHX_CODE_OVERLAY -I$(src)/support_ic/himax_0flash_mmi_hx83102d
ccflags-$(CONFIG_TOUCHSCREEN_HIMAX_ENABLE_PALM) += -DHIMAX_PALM_SENSOR_EN
ccflags-$(CONFIG_TOUCHSCREEN_HIMAX_ENABLE_DOUBLE_TAP) += -DHIMAX_V2_SENSOR_EN

obj-$(CONFIG_TOUCHSCREEN_HIMAX_SPI) += himax_0flash_mmi.o
himax_0flash_mmi-y += himax_common.o
himax_0flash_mmi-$(CONFIG_TOUCHSCREEN_HIMAX_SPI) += himax_platform_QCT_SPI.o
himax_0flash_mmi-$(CONFIG_TOUCHSCREEN_HIMAX_INSPECT) += himax_inspection.o
himax_0flash_mmi-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83112F) += support_ic/himax_0flash_mmi_hx83112f/himax_ic_HX83112f.o
himax_0flash_mmi-$(CONFIG_TOUCHSCREEN_HIMAX_IC_HX83112) += support_ic/himax_0flash_mmi_hx83112/himax_ic_HX83112.o
