ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI -DCONFIG_PANEL_NOTIFICATIONS

obj-$(CONFIG_TOUCHSCREEN_SEC_TS) += sec_mmi.o
sec_mmi-y += sec_ts.o sec_ts_fn.o sec_ts_fw.o sec_cmd.o sec_ts_only_vendor.o

ifdef CONFIG_INPUT_TOUCHSCREEN_MMI
    sec_mmi-y += sec_ts_mmi_class.o
else
    ccflags-y += -DUSE_STUBS
    sec_mmi-y += sec_ts_mmi.o
endif
