ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_MMI_CORE) += synaptics_mmi.o
synaptics_mmi-y += synaptics_dsx_i2c.o
synaptics_mmi-y += synaptics_mmi_class.o
synaptics_mmi-y += synaptics_dsx_instance.o

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_MMI_RMI_DEV) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_MMI_FW_UPDATE) += synaptics_dsx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_MMI_TEST_REPORTING) += synaptics_dsx_test_reporting.o
