ccflags-$(CONFIG_INPUT_TOUCHSCREEN_MMI) += -DCONFIG_INPUT_TOUCHSCREEN_MMI

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_SPI) += synaptics_bus/synaptics_spi.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_I2C) += synaptics_bus/synaptics_i2c.o

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_CORE) += synaptics_core_module.o
synaptics_core_module-y += synaptics_core/synaptics_core.o
synaptics_core_module-y += synaptics_core/synaptics_touch.o
synaptics_core_module-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_GESTURES) += synaptics_core/synaptics_ts_mmi.o

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_DEVICE) += synaptics_extmodules/synaptics_device.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_MMI_REFLASH) += synaptics_extmodules/synaptics_reflash.o
